version: '3.9'

services:
  python:
    build:
      context: ./python
    container_name: seo-python
    env_file:
      - ./python/.env
    ports:
      - "9002:9002"
    networks:
      - weamai_app-network

  node:
    build:
      context: ./node
    container_name: seo-node
    environment:
      - PORT=9001
      - PYTHON_API_PATH=http://python:9002
    env_file:
      - ./node/.env
    depends_on:
      - python
    ports:
      - "9001:9001"
    networks:
      - weamai_app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://node:9001
        VITE_API_PYTHON_URL: http://python:9002
    container_name: seo-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - node
      - python
    ports:
      - "3001:3001"
    networks:
      - weamai_app-network

networks:
  weamai_app-network:
    external: true
